### ISSUE TITLE
How do I set sideset?

### ISSUE THREAD

**Issue by eosulliv** [polyfem/polyfem-python#4]
From what I can tell, the sidesets are used to set the boundary condition for all meshes loaded by the PolyFEM solver. In some cases these are calculated automatically but it looks at though the function ``load_mesh_from_path_and_tags`` can be used to load a tetrahedral ``.mesh`` file with its tags.
What I want to know is how do I create a bc_tags text file? I couldnot find this covered in any tutorial and would appreciate any insight or help with this.

**Comment by teseoch** [comment]
Hi, the easiest way to set sidesets is with a lambda function. You can write a function that takes as input a point (face barycenter) and returns an integer for the sidesets. The function is `solver.set_boundary_side_set_from_bary`.

Here you can find an example:
https://geometryprocessing.github.io/geometric-computing-python/All/#advanced-sidesets

**Comment by eosulliv** [comment]
Thank you, this worked perfectly.
